### ISSUE TITLE
[BUG] Unable to start server, No check for menu_plugins

### ISSUE THREAD

**Issue by fixator10** [LUModder/SliMenu#1]
:arrow_down: **After enabling menu_plugins in settings** _I need to [download it](/glua/gmod-menu-plugins) separetly, right?_
![20160611165057_1](https://cloud.githubusercontent.com/assets/11073934/16089981/a17d0596-333e-11e6-97af-d0149f19b75b.jpg)

:arrow_down: **When trying launching an build-in server**
![20160611165018_1](https://cloud.githubusercontent.com/assets/11073934/16090009/bf8a1c2c-333e-11e6-9cb3-e06ead108266.jpg)

**Comment by LUModder** [comment]
Enabling menu_plugins seems to of fucked up your whole config file for some reason. Delete it from data (slimenu_config.txt). I'll look into why singleplayer isn't working

**Comment by fixator10** [comment]
![2016-06-25 23-31-54](https://cloud.githubusercontent.com/assets/11073934/16360703/8ab8ea9c-3b80-11e6-9065-22305e8794a7.png)
After removing config, still erroring. _(It's just clear menu, i didn't downloaded menu_plugins separately, if it needed. May be there must be check in code for installed menu_plugins?)_

**Comment by CaveeJohnson** [comment]
Fixed in https://github.com/LUModder/SliMenu/commit/13aa7ec998f6c161cc7f9eb4c835f0af99ce1541, you can close this now @LUModder
